DEBUG = True

WIN_WIDTH = 1200
WIN_HEIGHT = 600
LEVEL_RES = 40

CHAR_T_WIDTH = 64
CHAR_T_HEIGHT = 64
CHAR_WIDTH = 22
CHAR_HEIGHT = 46
CHAR_JUMP_SPEED = 10
CHAR_BASE_SPEED = 5
CHAR_POS_X = (WIN_WIDTH - CHAR_WIDTH) / 2
CHAR_POS_Y = 2 * (WIN_HEIGHT - CHAR_HEIGHT) / 3

GRAVITY = 1
MAX_FALL_SPEED = 30

SOLID = ['B']
